/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PersonalInfo = IDL.Record({
  'occupation' : IDL.Text,
  'height' : IDL.Text,
  'complexion' : IDL.Text,
  'placeOfBirth' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'caste' : IDL.Text,
  'name' : IDL.Text,
  'education' : IDL.Text,
  'manglikStatus' : IDL.Bool,
  'timeOfBirth' : IDL.Text,
  'income' : IDL.Text,
  'gotra' : IDL.Text,
  'religion' : IDL.Text,
});
export const FamilyInfo = IDL.Record({
  'familyType' : IDL.Text,
  'nativePlace' : IDL.Text,
  'motherOccupation' : IDL.Text,
  'motherName' : IDL.Text,
  'fatherName' : IDL.Text,
  'fatherOccupation' : IDL.Text,
  'siblingsInfo' : IDL.Text,
});
export const Horoscope = IDL.Record({
  'gan' : IDL.Text,
  'nadi' : IDL.Text,
  'charan' : IDL.Text,
  'nakshatra' : IDL.Text,
  'planetaryPositions' : IDL.Vec(IDL.Text),
  'rashi' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Biodata = IDL.Record({
  'contactInfo' : ContactInfo,
  'templatePreference' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'personalInfo' : PersonalInfo,
  'horoscope' : Horoscope,
  'familyInfo' : FamilyInfo,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createOrUpdateBiodata' : IDL.Func(
      [
        PersonalInfo,
        FamilyInfo,
        Horoscope,
        ContactInfo,
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteBiodata' : IDL.Func([], [], []),
  'getAllBiodatas' : IDL.Func([], [IDL.Vec(Biodata)], ['query']),
  'getBiodata' : IDL.Func([], [IDL.Opt(Biodata)], ['query']),
  'getBiodataByPrincipal' : IDL.Func([IDL.Principal], [Biodata], ['query']),
  'getPhoto' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getPhotoByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'searchBiodatasByCriteria' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Vec(Biodata)],
      ['query'],
    ),
  'searchBiodatasByName' : IDL.Func([IDL.Text], [IDL.Vec(Biodata)], ['query']),
  'uploadPhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PersonalInfo = IDL.Record({
    'occupation' : IDL.Text,
    'height' : IDL.Text,
    'complexion' : IDL.Text,
    'placeOfBirth' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'caste' : IDL.Text,
    'name' : IDL.Text,
    'education' : IDL.Text,
    'manglikStatus' : IDL.Bool,
    'timeOfBirth' : IDL.Text,
    'income' : IDL.Text,
    'gotra' : IDL.Text,
    'religion' : IDL.Text,
  });
  const FamilyInfo = IDL.Record({
    'familyType' : IDL.Text,
    'nativePlace' : IDL.Text,
    'motherOccupation' : IDL.Text,
    'motherName' : IDL.Text,
    'fatherName' : IDL.Text,
    'fatherOccupation' : IDL.Text,
    'siblingsInfo' : IDL.Text,
  });
  const Horoscope = IDL.Record({
    'gan' : IDL.Text,
    'nadi' : IDL.Text,
    'charan' : IDL.Text,
    'nakshatra' : IDL.Text,
    'planetaryPositions' : IDL.Vec(IDL.Text),
    'rashi' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Biodata = IDL.Record({
    'contactInfo' : ContactInfo,
    'templatePreference' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'personalInfo' : PersonalInfo,
    'horoscope' : Horoscope,
    'familyInfo' : FamilyInfo,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createOrUpdateBiodata' : IDL.Func(
        [
          PersonalInfo,
          FamilyInfo,
          Horoscope,
          ContactInfo,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteBiodata' : IDL.Func([], [], []),
    'getAllBiodatas' : IDL.Func([], [IDL.Vec(Biodata)], ['query']),
    'getBiodata' : IDL.Func([], [IDL.Opt(Biodata)], ['query']),
    'getBiodataByPrincipal' : IDL.Func([IDL.Principal], [Biodata], ['query']),
    'getPhoto' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getPhotoByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'searchBiodatasByCriteria' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Vec(Biodata)],
        ['query'],
      ),
    'searchBiodatasByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Biodata)],
        ['query'],
      ),
    'uploadPhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };