/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Biodata {
  'contactInfo' : ContactInfo,
  'templatePreference' : string,
  'photo' : [] | [ExternalBlob],
  'personalInfo' : PersonalInfo,
  'horoscope' : Horoscope,
  'familyInfo' : FamilyInfo,
}
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface FamilyInfo {
  'familyType' : string,
  'nativePlace' : string,
  'motherOccupation' : string,
  'motherName' : string,
  'fatherName' : string,
  'fatherOccupation' : string,
  'siblingsInfo' : string,
}
export interface Horoscope {
  'gan' : string,
  'nadi' : string,
  'charan' : string,
  'nakshatra' : string,
  'planetaryPositions' : Array<string>,
  'rashi' : string,
}
export interface PersonalInfo {
  'occupation' : string,
  'height' : string,
  'complexion' : string,
  'placeOfBirth' : string,
  'dateOfBirth' : string,
  'caste' : string,
  'name' : string,
  'education' : string,
  'manglikStatus' : boolean,
  'timeOfBirth' : string,
  'income' : string,
  'gotra' : string,
  'religion' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createOrUpdateBiodata' : ActorMethod<
    [
      PersonalInfo,
      FamilyInfo,
      Horoscope,
      ContactInfo,
      [] | [ExternalBlob],
      string,
    ],
    undefined
  >,
  'deleteBiodata' : ActorMethod<[], undefined>,
  'getAllBiodatas' : ActorMethod<[], Array<Biodata>>,
  'getBiodata' : ActorMethod<[], [] | [Biodata]>,
  'getBiodataByPrincipal' : ActorMethod<[Principal], Biodata>,
  'getPhoto' : ActorMethod<[], [] | [ExternalBlob]>,
  'getPhotoByPrincipal' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'searchBiodatasByCriteria' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [boolean]],
    Array<Biodata>
  >,
  'searchBiodatasByName' : ActorMethod<[string], Array<Biodata>>,
  'uploadPhoto' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];